services:
  cliente-persona-image:
    build: ./cliente-persona-servicio
    container_name: cliente-persona-microservice
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/devsu_test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Devsu_$2024
    depends_on:
      - db

  cuenta-movimientos-image:
    build: ./cuenta-movimientos-servicio
    container_name: cuenta-movimientos-microservice
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/devsu_test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Devsu_$2024
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Devsu_$2024
      MYSQL_DATABASE: devsu_test
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
